version: "3.4"

services:
  postgres:
    image: "postgres:12.2"
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=user-node
      - POSTGRES_DB=my-test
      - POSTGRES_PASSWORD=password321
    volumes:
      - "pgdata-backend:/var/lib/postgresql/data"

  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile
      context: .
      target: base
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/home/node/app
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - notused:/app/node_modules
    environment:
      - TZ=America/Mexico_City
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - PORT=5000
      - DB_USER=user-node
      - DB_HOST=postgres
      - DB_NAME=my-test
      - DB_PASSWORD=password321
      - DB_PORT=5432
      - DB_SSL=false
      - DB_DIALECT=postgres
      - ENV=development
      - URL_FRONTEND=http://localhost:8000
      - OL_EMAIL=equipo15.hackademy@outlook.com
      - OL_PASS=hackademyE15
      - JWT_ACCESS_SECRET=01a72f71f9ab5cb04dbf6c112af67733789ea95b88ef8ea437ac9d58505e820865cbd9f55290f8082bf2f10317746a755ce7d4eed58ee168333d3a1ab3a35271
      - JWT_REFRESH_SECRET=40086c8b92cf575726f272e6f9d0a9962d1bb9c6691c8c6f907a81e090f820181967ec24426a7e6b0bc79b2794d285c766d80eaa29eb29b5ad18e4ce162fc667
      - JWT_ACCESS_TIME=3h
      - JWT_REFRESH_TIME=30d
      - URL_HEROKU=https://mymoney15.herokuapp.com/api/v1
      - user= "equipo15.hackademy@gmail.com"
      - pass= "hackademyE15"
      


volumes:
  pgdata-backend:
  notused: